[package]
name = "cis_611_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = { version = "0.40.2" }
clap = { version = "3.2.22", features = ["derive"] }
anyhow = { version = "1.0.65" }
quit = { version = "1.1.4" }
